--Создание таблицы Абонентов
CREATE TABLE Subscribers(
  ID_MSISDM NUMBER NOT NULL,
  Name VARCHAR(25) NOT NULL,
  Gender VARCHAR(6) NOT NULL,
  CONSTRAINT MSISDM_PK PRIMARY KEY(ID_MSISDM)  
);

--Создание таблицы Карты
CREATE TABLE Cards(
  ID_PAN NUMBER NOT NULL,
  EXPIRE DATE NOT NULL,
  ID_MSISDM NUMBER NOT NULL,
  CONSTRAINT PAN_PK PRIMARY KEY(ID_PAN),
  CONSTRAINT MSISDM_ID FOREIGN KEY(ID_MSISDM) REFERENCES Subscribe(ID_MSISDM)
);

--Заполнения таблиц
INSERT INTO "SUBSCRIBERS" (ID_MSISDM, Name, Gender) VALUES ('1','Jack','муж');
INSERT INTO "SUBSCRIBERS" (ID_MSISDM, Name, Gender) VALUES ('2','JС','муж');
INSERT INTO "SUBSCRIBERS" (ID_MSISDM, Name, Gender) VALUES ('3','Emma','жен');
INSERT INTO "SUBSCRIBERS" (ID_MSISDM, Name, Gender) VALUES ('4','Lucas','муж');

INSERT INTO "CARDS" (ID_PAN, EXPIRE, ID_MSISDM) VALUES ('1', '22-11-2019', '1');
INSERT INTO "CARDS" (ID_PAN, EXPIRE, ID_MSISDM) VALUES ('2', '12-07-2020', '1');
INSERT INTO "CARDS" (ID_PAN, EXPIRE, ID_MSISDM) VALUES ('3', '16-01-2020', '1');
INSERT INTO "CARDS" (ID_PAN, EXPIRE, ID_MSISDM) VALUES ('4', '08-05-2024', '3');
INSERT INTO "CARDS" (ID_PAN, EXPIRE, ID_MSISDM) VALUES ('5', '01-01-2021', '2');
INSERT INTO "CARDS" (ID_PAN, EXPIRE, ID_MSISDM) VALUES ('6', '05-05-2025', '3');
INSERT INTO "CARDS" (ID_PAN, EXPIRE, ID_MSISDM) VALUES ('7', '09-08-2023', '4');
INSERT INTO "CARDS" (ID_PAN, EXPIRE, ID_MSISDM) VALUES ('8', '19-04-2019', '2');
INSERT INTO "CARDS" (ID_PAN, EXPIRE, ID_MSISDM) VALUES ('9', '28-10-2020', '2');
INSERT INTO "CARDS" (ID_PAN, EXPIRE, ID_MSISDM) VALUES ('10', '13-02-2022', '4');
INSERT INTO "CARDS" (ID_PAN, EXPIRE, ID_MSISDM) VALUES ('11', '20-02-2024', '1');

--Задание 2
CREATE OR REPLACE FUNCTION "NumberOfCards" (id NUMBER) RETURN NUMBER IS
coun NUMBER := 0;
BEGIN
  SELECT COUNT(ID_PAN)
  INTO coun
  FROM CARDS
  WHERE ID_MSISDM = id;
  RETURN coun;
END;

--Задание 3
CREATE TYPE "info_abonent" IS OBJECT (msisdm NUMBER, pan NUMBER, expire DATE);
/
CREATE OR REPLACE FUNCTION "GetInfoAbonent" (id NUMBER) RETURN "my_type" IS
result_abonent "my_type";
BEGIN
  SELECT SUBSCRIBERS.ID_MSISDM, CARDS.ID_PAN, CARDS.EXPIRE
  INTO result_abonent.msisdm, result_abonent.pan, result_abonent.expire
  FROM SUBSCRIBERS, CARDS
  WHERE SUBSCRIBERS.ID_MSISDM = id;
  RETURN result_abonent;
END;